home/urls.py
from django.urls import path, include
from .views import view_status

app_name="home"

urlpatterns = [
    path('', view_status, name="status"),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story7', include("story7.urls")),
    path('story8', include("story8.urls")),
    path('story9/', include("story9.urls"))
    
]

story7/urls.py
from django.urls import path, include
from .views import view_story7


app_name="Story7"
urlpatterns = [
    path('', view_story7, name="story7"),
]

story8/urls.py
from django.urls import path, include
from .views import view_story8


app_name="Story8"
urlpatterns = [
    path('', view_story8, name="story8"),
]

story9/urls.py
from django.urls import path, include
from .views import view_story9, view_login, view_logout

app_name="story9"
urlpatterns = [
    path('', view_story9, name="story9"),
    path('login/', view_login, name="login"),
    path('logout/', view_logout, name="logout")
]

home/models.py
from django.db import models

class Status(models.Model):
    status = models.CharField(max_length=300)
    time = models.DateTimeField(blank=True, null=True)

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.forms import widgets

class StatusForm(forms.Form):
    status = forms.CharField(label = "status", widget = forms.Textarea(attrs={"class": "statusfrm", "rows":20, "cols":205}))

home/views.py
from django.shortcuts import render, redirect
from .forms import StatusForm
from .models import Status
import datetime

def view_status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
          s = form.data['status']
        #   if(len(s)>300):
        #       s = s[0:300]
          s = s[0:300]
          status = Status(status = s, time = datetime.datetime.now())
          status.save()
          return redirect('/')
    else:
        form = StatusForm()
    status_objects = Status.objects.all().order_by("time").reverse()
    context = {'form': form, "status_objects": status_objects}
    return render(request, 'index.html', context)

story7/views.py
from django.shortcuts import render


# Create your views here.
def view_story7(request):
    return render(request, 'story7.html')

story8/views.py
from django.shortcuts import render

# Create your views
def view_story8(request):
    return render(request, 'story8.html')

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required



# Create your views
def view_story9(request):
    return render(request, 'home.html')

def view_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/story9')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def view_logout(request):
    logout(request)
    return redirect('/story9')

home/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Egi's Status</title>
</head>
<body>
    <h1 class="halo">Halo, apa kabar?</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" id="submit" value="post">
    </form>

    {% if status_objects %}
        {% for status in status_objects %}
            <div class="status">
                <h2 class="text">
                    {{ status.status }}
                </h2>
                <p class="time">{{ status.time|date:'d M Y | H:i' }}</p>
            </div>
        {% endfor %}
    {% endif %}
    
</body>
</html>

story7/templates/story7.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'story7.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
    <script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'story7.js' %}"></script>
    <title>Egi's Story 7</title>
</head>
<body>
    <div class="toggle-container">
        <div class="toggle"></div>
    </div>
    <h1>Hi, I'm Egi</h1>
    <div class="accordion">
        <div class="item activities">
            <h2 class="title" id="activities">Past Activities and Experiences</h2>
            <div class="desc">
                <p>1) Staff of Human Resources</p>
                <p>2) Head of Fundraising division</p>
                <p>3) Head of Human Resources class</p>
            </div>
        </div>
        <div class="item organizations">
            <h2 class="title" id="organizations">Organizations and Committees</h2>
            <div class="desc">
                <p>1) HR DPM Fasilkom UI</p>
                <p>2) Pemira IKM Fasilkom UI 2019</p>
                <p>3) SSD 2019</p>

            </div>
        </div>
        <div class="item achievements">
            <h2 class="title" id="achievements">Achievements</h2>
            <div class="desc">
                <p>1) Eaten 5 portions of instant noodle without help on 18th birthday</p>
                <p>2) Hunter Rank 300 in Monster Hunter World</p>
                <P>3) Killed a Furious Rajang</P>
            </div>
        </div>
    </div>
</body>
</html>

story8/templates/story8.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
    <script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
    <script src="{% static 'story8.js' %}"></script>
    <title>Story 8 Egi</title>
</head>
<body style="background-color:azure; font-family: 'Muli', sans-serif;">
    <h1>Search for books here!</h1>
    <input class="form-control" type="text" id="search" placeholder="Search here..." aria-label="Search" style="margin-left: 5px; margin-bottom: 20px; width: 500px; height: 50px; padding: 5px; border-radius: 10px;">
    <button type="button" id = "button" class="btn btn-dark" style="margin-left: 5px; margin-bottom: 20px;">Search</button>    
    <table class="table table-dark table-striped" id="books">
        <thead class="thead-dark">
          <tr>
            <th scope="col">title</th>
            <th scope="col">Book Cover</th>
            <th scope="col">Author</th>
            <th scope="col">Details</th>
          </tr>
        </thead>
    </table>
</body>
</html> 

story9/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Story 9 Egi</title>
</head>
<body style="text-align: center; margin-top: 20%;">

    {% if user.is_authenticated %}
    <h1>Hello, {{ user }}</h1>
    <a href="{% url 'story9:logout' %}">
        <button id="logout">Logout</button>
    </a>
    {% else %}
    <h1>
        Please login to visit this website!
    </h1>
    <a href="{% url 'story9:login' %}">
            <button id="login">Login</button>
    </a>
    {% endif %}

</body>
</html>

story9/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Story9</title>
</head>
<body style="text-align: center; margin-top: 20%;">
    <form class="auth-form" action="{% url 'story9:login' %}" method="POST">
        {% csrf_token %}
        <label for="id_username">Username:</label>
        <input type="text" name="username" autofocus="" required="" id="id_username">
        <br></br>
        <label for="id_password">Password:</label>
        <input type="password" name="password" required="" id="id_password">
        <br></br>
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" id="login" value="Login">
    </form>
</body>
</html>